### ISSUE TITLE
Ressources not loading in builds

### ISSUE THREAD

**Issue by LeithBA** [Lissandre/webpack_template#81]
You don't have to do much to reproduce this one since the base repo comes with a pre-installed font. Just build the project and run it.

Steps to reproduce:
1. Clone Repo `git clone https://github.com/Lissandre/webpack_template`
2. Change Directories `cd webpack_template`
3. Install Dependencies `npm install`
4. Build `npm run build`
5. Open dist/Index.html in browser

Result:
![image](https://user-images.githubusercontent.com/34186819/103093593-15378500-45fb-11eb-8fe0-ee1598d0b22a.png)
`Failed to load resource: net::ERR_FILE_NOT_FOUND` from `LOCAL_PATH/fonts/3cd786652b8a2e9d41f210cb1a527ff6.ttf`

Expected:
![image](https://user-images.githubusercontent.com/34186819/103093638-30a29000-45fb-11eb-8d25-421285c7f13a.png)

**Comment by Lissandre** [comment]
Thanks, it's maybe a bug related to the recent update I made to Webpack 5, I don't remember having this problem before. If you know how to fix this feel free to make a PR, otherwise I'll do it in the next days ✌️

**Comment by LeithBA** [comment]
Small update:
This bug seems to be happening for any ressource file not only fonts. I have also tried with a jpg image.

I still have no solution but I might have found the core of the problem.

**PROBLEM**
Once built the path of the referred file is wrong. For example in this case I am trying to load a font;
The path that gets generated is absolute and not relative to where the style file is.
`C:\Users\Leith\Documents\Repositories\webpack_template\dist/fonts/3cd786652b8a2e9d41f210cb1a527ff6.ttf`
This path can be found in the generated main.css file in the dist folder.


**HALF SOLUTION**
By changing it to `fonts/3cd786652b8a2e9d41f210cb1a527ff6.ttf` the font works.

Being a total webpack beginner, I am not sure how to make webpack generate the correct path. Any idea?

**Comment by Lissandre** [comment]
Can you try to add this in the exported module of `webpack.common.js` to see if there is any changes ?
```
node: {
    __dirname: 'mock',
  },
```

**Comment by LeithBA** [comment]
I just tried your suggestion; sadly it did not help.
I forgot to mention I am on windows 10 this time. I honestly did not think of testing on my computer at home, I'll try to do that on linux tonight.
I'll keep looking for a solution and will keep you posted.

I am curious, what path is generated for the font in your `main.css`?

Thanks for the help

**Comment by Lissandre** [comment]
Ok, the problem since to be on the style loader so I change the output path. I think that might be the good answer this time, can you check that ?
In `webpack.prod.js`, change the outputPath of the loader (in module) with `./` instead of what you have now.

**Comment by LeithBA** [comment]
It worked! I had to change the publicPath though and not the outputPath.
Thanks for the support. I see you fixed it already so I won't do a PR. Have a good one!
